=== Reagirre/DAW22_Klase_artxiboak/Jon Agirre/MARKATZEKO-LENGOAIAK/XML_ariketak/Xml/bin/kantak.dtd
<!ELEMENT kantak (kanta+)>
<!ELEMENT kanta (id, izenburua,egilea,urtea)>
<!ELEMENT id(#PCDATA)>
<!ELEMENT izenburua(#PCDATA)>
<!ELEMENT egilea(#PCDATA)>
<!ELEMENT urtea(#PCDATA)>

=== Reagirre/DAW22_Klase_artxiboak/Jon Agirre/MARKATZEKO-LENGOAIAK/XML_ariketak/Xml/lib/kantak.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE kantak SYSTEM "kantak.dtd">
<kantak>
        <kanta>
                <id>1</id>
                <izenburua>Like A Rolling Stone</izenburua>
                <egilea>Bob Dylan</egilea>
                <urtea>1965</urtea>
        </kanta>
        <kanta>
                <id>2</id>
                <izenburua>(I Can't Get No) Satisfaction</izenburua>
                <egilea>The Rolling Stones</egilea>
                <urtea>1965</urtea>
        </kanta>
        <kanta>
                <id>3</id>
                <izenburua>Imagine</izenburua>
                <egilea>John Lennon</egilea>
                <urtea>1971</urtea>
        </kanta>
        <kanta>
                <id>4</id>
                <izenburua>What's Going On</izenburua>
                <egilea>Marvin Gaye</egilea>
                <urtea>1971</urtea>
        </kanta>
        <kanta>
                <id>5</id>
                <izenburua>Respect</izenburua>
                <egilea>Aretha Franklin</egilea>
                <urtea>1967</urtea>
        </kanta>
        <kanta>
                <id>6</id>
                <izenburua>Good Vibrations</izenburua>
                <egilea>The Beach Boys</egilea>
                <urtea>1966</urtea>
        </kanta>
        <kanta>
                <id>7</id>
                <izenburua>Johnny B. Goode</izenburua>
                <egilea>Chuck Berry</egilea>
                <urtea>1958</urtea>
        </kanta>
        <kanta>
                <id>8</id>
                <izenburua>Hey Jude</izenburua>
                <egilea>The Beatles</egilea>
                <urtea>1968</urtea>
        </kanta>
        <kanta>
                <id>9</id>
                <izenburua>Smell Like Teen Spirit</izenburua>
                <egilea>Nirvana</egilea>
                <urtea>1991</urtea>
        </kanta>
        <kanta>
                <id>10</id>
                <izenburua>What'd I Say</izenburua>
                <egilea>Ray Charles</egilea>
                <urtea>1959</urtea>
        </kanta>
        <kanta>
                <id>11</id>
                <izenburua>My Generation</izenburua>
                <egilea>The Who</egilea>
                <urtea>1965</urtea>
        </kanta>
        <kanta>
                <id>12</id>
                <izenburua>A Change Is Gonna Come</izenburua>
                <egilea>Sam Cooke</egilea>
                <urtea>1964</urtea>
        </kanta>
        <kanta>
                <id>13</id>
                <izenburua>Yesterday</izenburua>
                <egilea>The Beatles</egilea>
                <urtea>1965</urtea>
        </kanta>
        <kanta>
                <id>14</id>
                <izenburua>Blowin' In The Wind</izenburua>
                <egilea>Bob Dylan</egilea>
                <urtea>1963</urtea>
        </kanta>
        <kanta>
                <id>15</id>
                <izenburua>London Calling</izenburua>
                <egilea>The Clash</egilea>
                <urtea>1980</urtea>
        </kanta>
        <kanta>
                <id>16</id>
                <izenburua>I Want To Hold Your Hand</izenburua>
                <egilea>The Beatles</egilea>
                <urtea>1963</urtea>
        </kanta>
        <kanta>
                <id>17</id>
                <izenburua>Purple Haze</izenburua>
                <egilea>The Jimi Hendrix Experience</egilea>
                <urtea>1967</urtea>
        </kanta>
        <kanta>
                <id>18</id>
                <izenburua>Maybellene</izenburua>
                <egilea>Chuck Berry</egilea>
                <urtea>1955</urtea>
        </kanta>
        <kanta>
                <id>19</id>
                <izenburua>Hound Dog</izenburua>
                <egilea>Elvis Presley</egilea>
                <urtea>1956</urtea>
        </kanta>
        <kanta>
                <id>20</id>
                <izenburua>Let It Be</izenburua>
                <egilea>The Beatles</egilea>
                <urtea>1970</urtea>
        </kanta>
        <kanta>
                <id>21</id>
                <izenburua>Born To Run</izenburua>
                <egilea>Bruce Springsteen</egilea>
                <urtea>1975</urtea>
        </kanta>
        <kanta>
                <id>22</id>
                <izenburua>Be My Baby</izenburua>
                <egilea>The Ronettes</egilea>
                <urtea>1963</urtea>
        </kanta>
        <kanta>
                <id>23</id>
                <izenburua>In My Life</izenburua>
                <egilea>The Beatles</egilea>
                <urtea>1965</urtea>
        </kanta>
        <kanta>
                <id>24</id>
                <izenburua>People Get Ready</izenburua>
                <egilea>The Impressions</egilea>
                <urtea>1965</urtea>
        </kanta>
        <kanta>
                <id>25</id>
                <izenburua>God Only Knows</izenburua>
                <egilea>The Beach Boys</egilea>
                <urtea>1966</urtea>
        </kanta>
        <kanta>
                <id>26</id>
                <izenburua>A Day In The Life</izenburua>
                <egilea>The Beatles</egilea>
                <urtea>1967</urtea>
        </kanta>
        <kanta>
                <id>27</id>
                <izenburua>Layla</izenburua>
                <egilea>Derek And The Dominos</egilea>
                <urtea>1970</urtea>
        </kanta>
        <kanta>
                <id>28</id>
                <izenburua>(Sittin' On) The Dock Of The Bay</izenburua>
                <egilea>Otis Redding</egilea>
                <urtea>1968</urtea>
        </kanta>
        <kanta>
                <id>29</id>
                <izenburua>Help!</izenburua>
                <egilea>The Beatles</egilea>
                <urtea>1965</urtea>
        </kanta>
        <kanta>
                <id>30</id>
                <izenburua>I Walk The Line</izenburua>
                <egilea>Johnny Cash</egilea>
                <urtea>1956</urtea>
        </kanta>
        <kanta>
                <id>31</id>
                <izenburua>Stairway To Heaven</izenburua>
                <egilea>Led Zeppelin</egilea>
                <urtea>1971</urtea>
        </kanta>
        <kanta>
                <id>32</id>
                <izenburua>Sympathy For The Devil</izenburua>
                <egilea>The Rolling Stones</egilea>
                <urtea>1968</urtea>
        </kanta>
        <kanta>
                <id>33</id>
                <izenburua>River Deep-Mountain High</izenburua>
                <egilea>Ike And Tina Turner</egilea>
                <urtea>1966</urtea>
        </kanta>
        <kanta>
                <id>34</id>
                <izenburua>You've Lost That Lovin' Feelin'</izenburua>
                <egilea>The Righteous Brothers</egilea>
                <urtea>1964</urtea>
        </kanta>
        <kanta>
                <id>35</id>
                <izenburua>Light My Fire</izenburua>
                <egilea>The Doors</egilea>
                <urtea>1967</urtea>
        </kanta>
        <kanta>
                <id>36</id>
                <izenburua>One</izenburua>
                <egilea>U2</egilea>
                <urtea>1991</urtea>
        </kanta>
        <kanta>
                <id>37</id>
                <izenburua>No Woman, No Cry</izenburua>
                <egilea>Bob Marley And The Wailers</egilea>
                <urtea>1975</urtea>
        </kanta>
        <kanta>
                <id>38</id>
                <izenburua>Gimme Shelter</izenburua>
                <egilea>The Rolling Stones</egilea>
                <urtea>1969</urtea>
        </kanta>
        <kanta>
                <id>39</id>
                <izenburua>That'll Be The Day</izenburua>
                <egilea>Buddy Holly And The Crickets</egilea>
                <urtea>1957</urtea>
        </kanta>
        <kanta>
                <id>40</id>
                <izenburua>Dancing In The Street</izenburua>
                <egilea>Martha And The Vandellas</egilea>
                <urtea>1964</urtea>
        </kanta>
        <kanta>
                <id>41</id>
                <izenburua>The Weight</izenburua>
                <egilea>The Band</egilea>
                <urtea>1968</urtea>
        </kanta>
        <kanta>
                <id>42</id>
                <izenburua>Waterloo Sunset</izenburua>
                <egilea>The Kinks</egilea>
                <urtea>1968</urtea>
        </kanta>
        <kanta>
                <id>43</id>
                <izenburua>Tutti-Frutti</izenburua>
                <egilea>Little Richard</egilea>
                <urtea>1955</urtea>
        </kanta>
        <kanta>
                <id>44</id>
                <izenburua>Georgia On My Mind</izenburua>
                <egilea>Ray Charles</egilea>
                <urtea>1960</urtea>
        </kanta>
        <kanta>
                <id>45</id>
                <izenburua>Heartbreak Hotel</izenburua>
                <egilea>Elvis Presley</egilea>
                <urtea>1956</urtea>
        </kanta>
        <kanta>
                <id>46</id>
                <izenburua>Heroes</izenburua>
                <egilea>David Bowie</egilea>
                <urtea>1977</urtea>
        </kanta>
        <kanta>
                <id>47</id>
                <izenburua>Bridge Over Troubled Water</izenburua>
                <egilea>Simon And Garfunkel</egilea>
                <urtea>1970</urtea>
        </kanta>
        <kanta>
                <id>48</id>
                <izenburua>All Along The Watchtower</izenburua>
                <egilea>The Jimi Hendrix Experience</egilea>
                <urtea>1976</urtea>
        </kanta>
        <kanta>
                <id>49</id>
                <izenburua>Hotel California</izenburua>
                <egilea>The Eagles</egilea>
                <urtea>1976</urtea>
        </kanta>
        <kanta>
                <id>50</id>
                <izenburua>The Tracks Of My Tears</izenburua>
