<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE diskoak [
        <!ELEMENT diskoak (diskoa+)>
        <!ELEMENT diskoa (izenburua,egilea,urtea,formatua,prezioa)>
        <!ATTLIST diskoa id NMTOKEN #REQUIRED>
        <!ELEMENT izenburua (#PCDATA)>
        <!ELEMENT egilea (#PCDATA)>
        <!ELEMENT urtea (#PCDATA)>
        <!ELEMENT formatua (#PCDATA)>
        <!ELEMENT prezioa (#PCDATA)>
]>
<diskoak>
        <diskoa id="1">
                <izenburua>Sgt. Pepper's Lonely Hearts Club Band</izenburua>
                <egilea>The Beatles</egilea>
                <urtea>1967</urtea>
                <formatua>Biniloa</formatua>
                <prezioa>24</prezioa>
        </diskoa>
        <diskoa id="2">
                <izenburua>Pet Sounds</izenburua>
                <egilea>The Beach Boys</egilea>
                <urtea>1966</urtea>
                <formatua>Biniloa</formatua>
                <prezioa>24</prezioa>
        </diskoa>
        <diskoa id="3">
                <izenburua>Revolver</izenburua>
                <egilea>The Beatles</egilea>
                <urtea>1966</urtea>
                <formatua>Biniloa</formatua>
                <prezioa>24</prezioa>
        </diskoa>
        <diskoa id="4">
                <izenburua>Highway 61 Revisited</izenburua>
                <egilea>Bob Dylan</egilea>
                <urtea>1965</urtea>
                <formatua>Biniloa</formatua>
                <prezioa>24</prezioa>
        </diskoa>
        <diskoa id="5">
                <izenburua>Rubber Soul</izenburua>
                <egilea>The Beatles</egilea>
                <urtea>1965</urtea>
                <formatua>Biniloa</formatua>
                <prezioa>24</prezioa>
        </diskoa>
        <diskoa id="6">
                <izenburua>What's Going On</izenburua>
                <egilea>Marvin Gaye</egilea>
                <urtea>1971</urtea>
                <formatua>Biniloa</formatua>
                <prezioa>24</prezioa>
        </diskoa>
        <diskoa id="7">
                <izenburua>Exile On Main Street</izenburua>
                <egilea>The Rolling Stones</egilea>
                <urtea>1972</urtea>
                <formatua>Biniloa</formatua>
                <prezioa>24</prezioa>
        </diskoa>
        <diskoa id="8">
                <izenburua>London Calling</izenburua>
                <egilea>The Clash</egilea>
                <urtea>1980</urtea>
                <formatua>Biniloa</formatua>
                <prezioa>24</prezioa>
        </diskoa>
        <diskoa id="9">
                <izenburua>Blonde On Blonde</izenburua>
                <egilea>Bob Dylan</egilea>
                <urtea>1966</urtea>
                <formatua>Biniloa</formatua>
                <prezioa>24</prezioa>
        </diskoa>
        <diskoa id="10">
                <izenburua>The Beatles (White Album)</izenburua>
                <egilea>The Beatles</egilea>
                <urtea>1968</urtea>
                <formatua>Biniloa</formatua>
                <prezioa>24</prezioa>
        </diskoa>
        <diskoa id="11">
                <izenburua>The Sun Sessions</izenburua>
                <egilea>Elvis Presley</egilea>
                <urtea>1976</urtea>
                <formatua>Biniloa</formatua>
                <prezioa>24</prezioa>
        </diskoa>
        <diskoa id="12">
                <izenburua>Kind Of Blue</izenburua>
                <egilea>Miles Davis</egilea>
                <urtea>1959</urtea>
                <formatua>Biniloa</formatua>
                <prezioa>24</prezioa>
        </diskoa>
        <diskoa id="13">
                <izenburua>The Velvet Underground</izenburua>
                <egilea>The Velvet Underground And Nico</egilea>
                <urtea>1967</urtea>
                <formatua>Biniloa</formatua>
                <prezioa>24</prezioa>
        </diskoa>
        <diskoa id="14">
                <izenburua>Abbey Road</izenburua>
                <egilea>The Beatles</egilea>
                <urtea>1969</urtea>
                <formatua>Biniloa</formatua>
                <prezioa>24</prezioa>
        </diskoa>
        <diskoa id="15">
                <izenburua>Are You Experienced?</izenburua>
                <egilea>The Jimi Hendrix Experience</egilea>
                <urtea>1967</urtea>
                <formatua>Biniloa</formatua>
                <prezioa>24</prezioa>
        </diskoa>
        <diskoa id="16">
                <izenburua>Blood On The Tracks</izenburua>
                <egilea>Bob Dylan</egilea>
                <urtea>1975</urtea>
                <formatua>Biniloa</formatua>
                <prezioa>24</prezioa>
        </diskoa>
        <diskoa id="17">
                <izenburua>Nevermind</izenburua>
                <egilea>Nirvana</egilea>
                <urtea>1991</urtea>
                <formatua>Biniloa</formatua>
                <prezioa>24</prezioa>
        </diskoa>
        <diskoa id="18">
                <izenburua>Born To Run</izenburua>
                <egilea>Bruce Springsteen</egilea>
                <urtea>1975</urtea>
                <formatua>Biniloa</formatua>
                <prezioa>24</prezioa>
        </diskoa>
        <diskoa id="19">
                <izenburua>Astral Weeks</izenburua>
                <egilea>Van Morrison</egilea>
                <urtea>1968</urtea>
                <formatua>Biniloa</formatua>
                <prezioa>24</prezioa>
        </diskoa>
        <diskoa id="20">
                <izenburua>Thriller</izenburua>
                <egilea>Michael Jackson</egilea>
                <urtea>1982</urtea>
                <formatua>Biniloa</formatua>
                <prezioa>24</prezioa>
        </diskoa>
        <diskoa id="21">
                <izenburua>The Great Twenty-Eight</izenburua>
                <egilea>Chuck Berry</egilea>
                <urtea>1982</urtea>
                <formatua>Biniloa</formatua>
                <prezioa>24</prezioa>
        </diskoa>
        <diskoa id="22">
                <izenburua>Plastic Ono Band</izenburua>
                <egilea>John Lennon</egilea>
                <urtea>1970</urtea>
                <formatua>Biniloa</formatua>
                <prezioa>24</prezioa>
        </diskoa>
        <diskoa id="23">
                <izenburua>Innervisions</izenburua>
                <egilea>Stevie Wonder</egilea>
                <urtea>1973</urtea>
                <formatua>Biniloa</formatua>
                <prezioa>24</prezioa>
        </diskoa>
        <diskoa id="24">
                <izenburua>Live At The Apollo</izenburua>
                <egilea>James Brown</egilea>
                <urtea>1963</urtea>
                <formatua>Biniloa</formatua>
                <prezioa>24</prezioa>
        </diskoa>
        <diskoa id="25">
                <izenburua>Rumours</izenburua>
                <egilea>Fleetwood Mac</egilea>
                <urtea>1977</urtea>
                <formatua>Biniloa</formatua>
                <prezioa>24</prezioa>
        </diskoa>
        <diskoa id="26">
                <izenburua>The Joshua Tree</izenburua>
                <egilea>U2</egilea>
                <urtea>1987</urtea>
                <formatua>Biniloa</formatua>
                <prezioa>24</prezioa>
        </diskoa>
        <diskoa id="27">
                <izenburua>King Of The Delta Blues Singers</izenburua>
                <egilea>Robert Johnson</egilea>
                <urtea>1961</urtea>
                <formatua>Biniloa</formatua>
                <prezioa>24</prezioa>
        </diskoa>
        <diskoa id="28">
                <izenburua>Who's Next</izenburua>
                <egilea>The Who</egilea>
                <urtea>1971</urtea>
                <formatua>Biniloa</formatua>
                <prezioa>24</prezioa>
        </diskoa>
        <diskoa id="29">
                <izenburua>Led Zeppelin</izenburua>
                <egilea>Led Zeppelin</egilea>
                <urtea>1969</urtea>
                <formatua>Biniloa</formatua>
                <prezioa>24</prezioa>
        </diskoa>
        <diskoa id="30">
                <izenburua>Blue</izenburua>
                <egilea>Joni Mitchell</egilea>
                <urtea>1971</urtea>
                <formatua>Biniloa</formatua>
                <prezioa>24</prezioa>
        </diskoa>
        <diskoa id="31">
                <izenburua>Bringing It All Back Home</izenburua>
                <egilea>Bob Dylan</egilea>
                <urtea>1965</urtea>
                <formatua>Biniloa</formatua>
                <prezioa>24</prezioa>
        </diskoa>
        <diskoa id="32">
                <izenburua>Let It Bleed</izenburua>
                <egilea>The Rolling Stones</egilea>
                <urtea>1969</urtea>
                <formatua>Biniloa</formatua>
                <prezioa>24</prezioa>
        </diskoa>
        <diskoa id="33">
                <izenburua>Ramones</izenburua>
                <egilea>Ramones</egilea>
                <urtea>1976</urtea>
                <formatua>Biniloa</formatua>
                <prezioa>24</prezioa>
        </diskoa>
        <diskoa id="34">
                <izenburua>Music From Big Pink</izenburua>
                <egilea>The Band</egilea>
                <urtea>1968</urtea>
                <formatua>Biniloa</formatua>
                <prezioa>24</prezioa>
        </diskoa>
        <diskoa id="35">
                <izenburua>The Rise Rise And Fall Of Ziggy Stardust And The Spiders From Mars</izenburua>
                <egilea>David Bowie</egilea>
                <urtea>1972</urtea>
                <formatua>Biniloa</formatua>
                <prezioa>24</prezioa>
        </diskoa>
        <diskoa id="36">
                <izenburua>Tapestry</izenburua>
                <egilea>Carole King</egilea>
                <urtea>1971</urtea>
                <formatua>Biniloa</formatua>
                <prezioa>24</prezioa>
        </diskoa>
        <diskoa id="37">
                <izenburua>Hotel California</izenburua>
                <egilea>The Eagles</egilea>
                <urtea>1976</urtea>
                <formatua>Biniloa</formatua>
                <prezioa>24</prezioa>
        </diskoa>
        <diskoa id="38">
                <izenburua>The Anthology</izenburua>
                <egilea>Muddy Waters</egilea>
                <urtea>2001</urtea>
                <formatua>Biniloa</formatua>
                <prezioa>24</prezioa>
        </diskoa>
        <diskoa id="39">
                <izenburua>Please Please Me</izenburua>
                <egilea>The Beatles</egilea>
                <urtea>1963</urtea>
                <formatua>Biniloa</formatua>
                <prezioa>24</prezioa>
        </diskoa>
        <diskoa id="40">
                <izenburua>Forever Changes</izenburua>
                <egilea>Love</egilea>
                <urtea>1967</urtea>
                <formatua>Biniloa</formatua>
                <prezioa>24</prezioa>
        </diskoa>
        <diskoa id="41">
                <izenburua>Never Mind The Bollocks, Here's The Sex Pistols</izenburua>
                <egilea>The Sex Pistols</egilea>
                <urtea>1977</urtea>
                <formatua>Biniloa</formatua>
                <prezioa>24</prezioa>
        </diskoa>
        <diskoa id="42">
                <izenburua>The Doors</izenburua>
                <egilea>The Doors</egilea>
                <urtea>1967</urtea>
                <formatua>Biniloa</formatua>
                <prezioa>24</prezioa>
        </diskoa>
        <diskoa id="43">
                <izenburua>The Dark Side Of The Moon</izenburua>
                <egilea>Pink Floyd</egilea>
                <urtea>1973</urtea>
                <formatua>Biniloa</formatua>
                <prezioa>24</prezioa>
        </diskoa>
        <diskoa id="44">
                <izenburua>Horses</izenburua>
                <egilea>Patty Smith</egilea>
                <urtea>1975</urtea>
                <formatua>Biniloa</formatua>
                <prezioa>24</prezioa>
        </diskoa>
        <diskoa id="45">
                <izenburua>The Band</izenburua>
                <egilea>The Band</egilea>
                <urtea>1969</urtea>
                <formatua>Biniloa</formatua>
                <prezioa>24</prezioa>
        </diskoa>
        <diskoa id="46">
                <izenburua>Legend</izenburua>
                <egilea>Bob Marley And The Wailers</egilea>
                <urtea>1984</urtea>
                <formatua>Biniloa</formatua>
                <prezioa>24</prezioa>
        </diskoa>
        <diskoa id="47">
                <izenburua>A Love Supreme</izenburua>
                <egilea>John Coltrane</egilea>
                <urtea>1964</urtea>
                <formatua>Biniloa</formatua>
                <prezioa>24</prezioa>
        </diskoa>
        <diskoa id="48">
                <izenburua>It Takes A Nation Of Millions To Hold Us Back</izenburua>
                <egilea>Public Enemy</egilea>
                <urtea>1988</urtea>
                <formatua>Biniloa</formatua>
                <prezioa>24</prezioa>
        </diskoa>
        <diskoa id="49">
                <izenburua>At Fillmore East</izenburua>
                <egilea>The Allman Brothers Band</egilea>
                <urtea>1971</urtea>
                <formatua>Biniloa</formatua>
                <prezioa>24</prezioa>
        </diskoa>
        <diskoa id="50">
                <izenburua>Here's Little Richard</izenburua>
                <egilea>Little Richard</egilea>
                <urtea>1957</urtea>
                <formatua>Biniloa</formatua>
                <prezioa>24</prezioa>
        </diskoa>
        <diskoa id="51">
                <izenburua>Bridge Over Troubled Water</izenburua>
                <egilea>Simon And Garfunkel</egilea>
                <urtea>1970</urtea>
                <formatua>Biniloa</formatua>
                <prezioa>24</prezioa>
        </diskoa>
        <diskoa id="52">
                <izenburua>Greatest Hits</izenburua>
                <egilea>Al Green</egilea>
                <urtea>1975</urtea>
                <formatua>Biniloa</formatua>
                <prezioa>24</prezioa>
        </diskoa>
        <diskoa id="53">
                <izenburua>The Birth Of Soul: The Complete Atlantic R&amp;B</izenburua>
                <egilea>Ray Charles</egilea>
                <urtea>1991</urtea>
                <formatua>Biniloa</formatua>
                <prezioa>24</prezioa>
        </diskoa>
        <diskoa id="54">
                <izenburua>Electric Ladyland</izenburua>
                <egilea>The Jimi Hendrix Experience</egilea>
                <urtea>1968</urtea>
                <formatua>Biniloa</formatua>
                <prezioa>24</prezioa>
        </diskoa>
        <diskoa id="55">
                <izenburua>Elvis Presley</izenburua>
                <egilea>Elvis Presley</egilea>
                <urtea>1956</urtea>
                <formatua>Biniloa</formatua>
                <prezioa>24</prezioa>
        </diskoa>
        <diskoa id="56">
                <izenburua>Songs In The Key Of Life</izenburua>
                <egilea>Stevie Wonder</egilea>
                <urtea>1976</urtea>
                <formatua>Biniloa</formatua>
                <prezioa>24</prezioa>
        </diskoa>
        <diskoa id="57">
                <izenburua>Beggars Banquet</izenburua>
                <egilea>The Rolling Stones</egilea>
                <urtea>1968</urtea>
                <formatua>Biniloa</formatua>
                <prezioa>24</prezioa>
        </diskoa>
        <diskoa id="58">
                <izenburua>Trout Mask Replica</izenburua>
                <egilea>Captain Beefheart And His Magic Band</egilea>
                <urtea>1969</urtea>
                <formatua>Biniloa</formatua>
                <prezioa>24</prezioa>
        </diskoa>
        <diskoa id="59">
                <izenburua>Meet The Beatles</izenburua>
                <egilea>The Beatles</egilea>
                <urtea>1964</urtea>
                <formatua>Biniloa</formatua>
                <prezioa>24</prezioa>
        </diskoa>
        <diskoa id="60">
                <izenburua>Greatest Hits</izenburua>
                <egilea>Sly And The Family Stone</egilea>
                <urtea>1970</urtea>
                <formatua>Biniloa</formatua>
                <prezioa>24</prezioa>
        </diskoa>
        <diskoa id="61">
                <izenburua>Appetite For Destruction</izenburua>
                <egilea>Guns N'Roses</egilea>
                <urtea>1987</urtea>
                <formatua>Biniloa</formatua>
                <prezioa>24</prezioa>
        </diskoa>
        <diskoa id="62">
                <izenburua>Achtung Baby</izenburua>
                <egilea>U2</egilea>
                <urtea>1991</urtea>
                <formatua>Biniloa</formatua>
                <prezioa>24</prezioa>
        </diskoa>
        <diskoa id="63">
                <izenburua>Sticky Fingers</izenburua>
                <egilea>The Rolling Stones</egilea>
                <urtea>1971</urtea>
                <formatua>Biniloa</formatua>
                <prezioa>24</prezioa>
        </diskoa>
        <diskoa id="64">
                <izenburua>Back To Mono (1958-1969)</izenburua>
                <egilea>Phil Spector</egilea>
                <urtea>1991</urtea>
                <formatua>Biniloa</formatua>
                <prezioa>24</prezioa>
        </diskoa>
        <diskoa id="65">
                <izenburua>Moondance</izenburua>
                <egilea>Van Morrison</egilea>
                <urtea>1970</urtea>
                <formatua>Biniloa</formatua>
                <prezioa>24</prezioa>
        </diskoa>
        <diskoa id="66">
                <izenburua>Led Zeppelin IV</izenburua>
                <egilea>Led Zeppelin</egilea>
                <urtea>1971</urtea>
                <formatua>Biniloa</formatua>
                <prezioa>24</prezioa>
        </diskoa>
        <diskoa id="67">
                <izenburua>The Stranger</izenburua>
                <egilea>Billy Joel</egilea>
                <urtea>1977</urtea>
                <formatua>Biniloa</formatua>
                <prezioa>24</prezioa>
        </diskoa>
        <diskoa id="68">
                <izenburua>Off The Wall</izenburua>
                <egilea>Michael Jackson</egilea>
                <urtea>1979</urtea>
                <formatua>Biniloa</formatua>
                <prezioa>24</prezioa>
        </diskoa>
        <diskoa id="69">
                <izenburua>Superfly</izenburua>
                <egilea>Curtis Mayfield</egilea>
                <urtea>1972</urtea>
                <formatua>Biniloa</formatua>
                <prezioa>24</prezioa>
        </diskoa>
        <diskoa id="70">
                <izenburua>Physical Graffiti</izenburua>
                <egilea>Led Zeppelin</egilea>
                <urtea>1975</urtea>
                <formatua>Biniloa</formatua>
                <prezioa>24</prezioa>
        </diskoa>
        <diskoa id="71">
                <izenburua>After The Gold Rush</izenburua>
                <egilea>Neil Young</egilea>
                <urtea>1970</urtea>
                <formatua>Biniloa</formatua>
                <prezioa>24</prezioa>
        </diskoa>
        <diskoa id="72">
                <izenburua>Purple Rain</izenburua>
                <egilea>Prince And The Revolution</egilea>
                <urtea>1984</urtea>
                <formatua>Biniloa</formatua>
                <prezioa>24</prezioa>
        </diskoa>
        <diskoa id="73">
                <izenburua>Back In Black</izenburua>
                <egilea>AC/DC</egilea>
                <urtea>1980</urtea>
                <formatua>Biniloa</formatua>
                <prezioa>24</prezioa>
        </diskoa>
        <diskoa id="74">
                <izenburua>Otis Blue</izenburua>
                <egilea>Otis Redding</egilea>
                <urtea>1965</urtea>
                <formatua>Biniloa</formatua>
                <prezioa>24</prezioa>
        </diskoa>
        <diskoa id="75">
                <izenburua>Led Zeppelin II</izenburua>
                <egilea>Led Zeppelin</egilea>
                <urtea>1969</urtea>
                <formatua>Biniloa</formatua>
                <prezioa>24</prezioa>
        </diskoa>
        <diskoa id="76">
                <izenburua>Imagine</izenburua>
                <egilea>John Lennon</egilea>
                <urtea>1971</urtea>
                <formatua>Biniloa</formatua>
                <prezioa>24</prezioa>
        </diskoa>
        <diskoa id="77">
                <izenburua>The Clash</izenburua>
                <egilea>The Clash</egilea>
                <urtea>1977</urtea>
                <formatua>Biniloa</formatua>
                <prezioa>24</prezioa>
        </diskoa>
        <diskoa id="78">
                <izenburua>Harvest</izenburua>
                <egilea>Neil Young</egilea>
                <urtea>1972</urtea>
                <formatua>Biniloa</formatua>
                <prezioa>24</prezioa>
        </diskoa>
        <diskoa id="79">
                <izenburua>Star Time</izenburua>
                <egilea>James Brown</egilea>
                <urtea>1991</urtea>
                <formatua>Biniloa</formatua>
                <prezioa>24</prezioa>
        </diskoa>
        <diskoa id="80">
                <izenburua>Odessey And Oracle</izenburua>
                <egilea>The Zombies</egilea>
                <urtea>1969</urtea>
                <formatua>Biniloa</formatua>
                <prezioa>24</prezioa>
        </diskoa>
        <diskoa id="81">
                <izenburua>Graceland</izenburua>
                <egilea>Paul Simon</egilea>
                <urtea>1986</urtea>
                <formatua>Biniloa</formatua>
                <prezioa>24</prezioa>
        </diskoa>
        <diskoa id="82">
                <izenburua>Axis: Bold As Love</izenburua>
                <egilea>The Jimi Hendrix Experience</egilea>
                <urtea>1968</urtea>
                <formatua>Biniloa</formatua>
                <prezioa>24</prezioa>
        </diskoa>
        <diskoa id="83">
                <izenburua>I Never Loved A Man The Way I Love You</izenburua>
                <egilea>Aretha Franklin</egilea>
                <urtea>1967</urtea>
                <formatua>Biniloa</formatua>
                <prezioa>24</prezioa>
        </diskoa>
        <diskoa id="84">
                <izenburua>Lady Soul</izenburua>
                <egilea>Aretha Franklin</egilea>
                <urtea>1968</urtea>
                <formatua>Biniloa</formatua>
                <prezioa>24</prezioa>
        </diskoa>
        <diskoa id="85">
                <izenburua>Born In The U.S.A.</izenburua>
                <egilea>Bruce Springsteen</egilea>
                <urtea>1984</urtea>
                <formatua>Biniloa</formatua>
                <prezioa>24</prezioa>
        </diskoa>
        <diskoa id="86">
                <izenburua>Let It Be</izenburua>
                <egilea>The Beatles</egilea>
                <urtea>1970</urtea>
                <formatua>Biniloa</formatua>
                <prezioa>24</prezioa>
        </diskoa>
        <diskoa id="87">
                <izenburua>The Wall</izenburua>
                <egilea>Pink Floyd</egilea>
                <urtea>1979</urtea>
                <formatua>Biniloa</formatua>
                <prezioa>24</prezioa>
        </diskoa>
        <diskoa id="88">
                <izenburua>At Folsom Prison</izenburua>
                <egilea>Johnny Cash</egilea>
                <urtea>1968</urtea>
                <formatua>Biniloa</formatua>
                <prezioa>24</prezioa>
        </diskoa>
        <diskoa id="89">
                <izenburua>Dusty In Memphis</izenburua>
                <egilea>Dusty Springfield</egilea>
                <urtea>1969</urtea>
                <formatua>Biniloa</formatua>
                <prezioa>24</prezioa>
        </diskoa>
        <diskoa id="90">
                <izenburua>Talking Book</izenburua>
                <egilea>Stevie Wonder</egilea>
                <urtea>1972</urtea>
                <formatua>Biniloa</formatua>
                <prezioa>24</prezioa>
        </diskoa>
        <diskoa id="91">
                <izenburua>Goodbye Yellow Brick Road</izenburua>
                <egilea>Elton John</egilea>
                <urtea>1973</urtea>
                <formatua>Biniloa</formatua>
                <prezioa>24</prezioa>
        </diskoa>
        <diskoa id="92">
                <izenburua>20 Golden Greats</izenburua>
                <egilea>Buddy Holly</egilea>
                <urtea>1978</urtea>
                <formatua>Biniloa</formatua>
                <prezioa>24</prezioa>
        </diskoa>
        <diskoa id="93">
                <izenburua>Sign 'o' The Times</izenburua>
                <egilea>Prince</egilea>
                <urtea>1987</urtea>
                <formatua>Biniloa</formatua>
                <prezioa>24</prezioa>
        </diskoa>
        <diskoa id="94">
                <izenburua>Bitches Brew</izenburua>
                <egilea>Miles Davis</egilea>
                <urtea>1970</urtea>
                <formatua>Biniloa</formatua>
                <prezioa>24</prezioa>
        </diskoa>
        <diskoa id="95">
                <izenburua>Green River</izenburua>
                <egilea>Creedence Clearwater Revival</egilea>
                <urtea>1969</urtea>
                <formatua>Biniloa</formatua>
                <prezioa>24</prezioa>
        </diskoa>
        <diskoa id="96">
                <izenburua>Tommy</izenburua>
                <egilea>The Who</egilea>
                <urtea>1969</urtea>
                <formatua>Biniloa</formatua>
                <prezioa>24</prezioa>
        </diskoa>
        <diskoa id="97">
                <izenburua>The Freewheelin' Bob Dylan</izenburua>
                <egilea>Bob Dylan</egilea>
                <urtea>1963</urtea>
                <formatua>Biniloa</formatua>
                <prezioa>24</prezioa>
        </diskoa>
        <diskoa id="98">
                <izenburua>This Year's Model</izenburua>
                <egilea>Elvis Costello</egilea>
                <urtea>1978</urtea>
                <formatua>Biniloa</formatua>
                <prezioa>24</prezioa>
        </diskoa>
        <diskoa id="99">
                <izenburua>There's A Riot Goin' On</izenburua>
                <egilea>Sly And The Family Stone</egilea>
                <urtea>1971</urtea>
                <formatua>Biniloa</formatua>
                <prezioa>24</prezioa>
        </diskoa>
        <diskoa id="100">
                <izenburua>In The Wee Small Hours</izenburua>
                <egilea>Frank Sinatra</egilea>
                <urtea>1955</urtea>
                <formatua>Biniloa</formatua>
                <prezioa>24</prezioa>
        </diskoa>
        <diskoa id="101">
                <izenburua>Fresh Cream</izenburua>
                <egilea>Cream</egilea>
                <urtea>1967</urtea>
                <formatua>Biniloa</formatua>
                <prezioa>24</prezioa>
        </diskoa>
        <diskoa id="102">
                <izenburua>Giant Steps</izenburua>
                <egilea>John Coltrane</egilea>
                <urtea>1960</urtea>
                <formatua>Biniloa</formatua>
                <prezioa>24</prezioa>
        </diskoa>
        <diskoa id="103">
                <izenburua>Sweet Baby James</izenburua>
                <egilea>James Taylor</egilea>
                <urtea>1970</urtea>
                <formatua>Biniloa</formatua>
                <prezioa>24</prezioa>
        </diskoa>
        <diskoa id="104">
                <izenburua>Modern Sounds In Country And Western Music</izenburua>
                <egilea>Ray Charles</egilea>
                <urtea>1962</urtea>
                <formatua>Biniloa</formatua>
                <prezioa>24</prezioa>
        </diskoa>
        <diskoa id="105">
                <izenburua>Rocket To Russia</izenburua>
                <egilea>Ramones</egilea>
                <urtea>1977</urtea>
                <formatua>Biniloa</formatua>
                <prezioa>24</prezioa>
        </diskoa>
        <diskoa id="106">
                <izenburua>Portrait Of A Legend 1951-1964</izenburua>
                <egilea>Sam Cooke</egilea>
                <urtea>2003</urtea>
                <formatua>Biniloa</formatua>
                <prezioa>24</prezioa>
        </diskoa>
        <diskoa id="107">
                <izenburua>Hunky Dory</izenburua>
                <egilea>David Bowie</egilea>
                <urtea>1970</urtea>
                <formatua>Biniloa</formatua>
                <prezioa>24</prezioa>
        </diskoa>
        <diskoa id="108">
                <izenburua>Aftermath</izenburua>
                <egilea>The Rolling Stones</egilea>
                <urtea>1966</urtea>
                <formatua>Biniloa</formatua>
                <prezioa>24</prezioa>
        </diskoa>
        <diskoa id="109">
                <izenburua>Loaded</izenburua>
                <egilea>The Velvet Underground</egilea>
                <urtea>1970</urtea>
                <formatua>Biniloa</formatua>
                <prezioa>24</prezioa>
        </diskoa>
        <diskoa id="110">
                <izenburua>The Bends</izenburua>
                <egilea>Radiohead</egilea>
                <urtea>1955</urtea>
                <formatua>Biniloa</formatua>
                <prezioa>24</prezioa>
        </diskoa>
        <diskoa id="111">
                <izenburua>Court And Spark</izenburua>
                <egilea>Joni Mitchell</egilea>
                <urtea>1974</urtea>
                <formatua>Biniloa</formatua>
                <prezioa>24</prezioa>
        </diskoa>
        <diskoa id="112">
                <izenburua>Disraeli Gears</izenburua>
                <egilea>Cream</egilea>